# fly.toml app configuration file generated for openclaw-telegram-bot-lxagvg on 2026-03-16T20:59:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "openclaw-telegram-bot-lxagvg"
primary_region = "ams"

[env]
NODE_OPTIONS="--max-old-space-size=1536"

[[vm]]
cpu_kind = "shared"
cpus = 2
memory = "2gb"
memory_mb = 2048